# Change these first
owner: alefvanoon # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Blog
    url: https://alefvanoon.xyz
  - name: Whoogle
    url: https://s.alefvanoon.xyz
  - name: Metasearch
    url: https://ss.alefvanoon.xyz
  - name: Nitter
    url: https://nitter.alefvanoon.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain.
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there.
  cname: status.alefvanoon.xyz
  # baseUrl: /your-repo-name
  themeUrl: https://raw.githubusercontent.com/alefvanoon/Status/gh-pages/themes/dark.css
  logoUrl: https://alefvanoon.xyz/assets/img/avatar.jpg
  name: Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/alefvanoon/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
