# Change these first
owner: alefvanoon # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Blog
    url: https://alefvanoon.xyz
  - name: Whoogle
    url: https://s.alefvanoon.xyz
  - name: Metasearch
    url: https://ss.alefvanoon.xyz
  - name: Nitter
    url: https://nitter.alefvanoon.xyz
  - name: Libreddit
    url: https://libreddit.alefvanoon.xyz
  - name: CloudTube
    url: https://tube.alefvanoon.xyz
  - name: Bibliogram
    url: https://biblio.alefvanoon.xyz
  - name: Searx
    url: https://sx.alefvanoon.xyz
  - name: Translate
    url: https://translate.alefvanoon.xyz
  - name: WBO
    url: https://wbo.alefvanoon.xyz
  - name: HedgeDoc
    url: https://mdpad.alefvanon.xyz
  - name: RSS-Bridge
    url: https://rssb.alefvanon.xyz
  - name: ytdl
    url: https://yt.alefvanon.xyz
  - name: invidious
    url: https://inv.alefvanoon.xyz
  - name: Piped-API
    url: https://pipedapi.alefvanoon.xyz
  - name: PipedP
    url: https://pipedp.alefvanoon.xyz
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain.
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there.
  cname: status.alefvanoon.xyz
  # baseUrl: /your-repo-name
  themeUrl: https://raw.githubusercontent.com/alefvanoon/Status/gh-pages/themes/dark.css
  logoUrl: https://alefvanoon.xyz/assets/img/avatar.jpg
  name: alefvanoon Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO 
